server:
  port: 9000
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka,http://127.0.0.1:10011/eureka
zuul:
  routes:
    consumer-server:  #默认为每个微服务都生成了匹配规则
      path: /consumer/**
      serviceId: consumer-server
      strip-prefix: false

  host: #ribbon的超时时间要小于zuul超时时间 。
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  ignored-services: user-server
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：6000ms
